### PR TITLE
fix(all/jellyfin): fix subtitles, pages, and some small code refactoring

### LINKED ISSUE #1548: Jellyfin: "No results found" but there are results
### Source information and language

Jellyfin 13.6 (Multi)

### Steps to reproduce

1. Open Aniyomi
2. Go to your Jellyfin extension
3. There's a "No results found" pop-up in the bottom even though there are results and it's bugging me.

### Expected behavior

The pop up "No results found" should not appear since there are results.

### Actual behavior

instead, it pop-up "No results found" even though there are results found.
Screenshot_20230429-111645

### Aniyomi version

App version: v0.14.3-6147 (mpv) , also tried in v0.12.3.10 (stable)

### Android version

Android 11

### Other details

Are there any problem with my Jellyfin, or is it a problem with the extension? Well, it works properly and I can also watch, but that pop-up "No results found" is really bugging me.

Here's the structure of my folder for Jellyfin Library:

Anime (Main Folder)
- Series 1 Name (Folder)
   - Season 1 (Folder)
     - Episodes.mp4
   - Season 2 (Folder)
     - Episodes.mp4
- Series 2 Name
   - ...
     - ...

It work properly on Jellyfin web & app, but I just prefer to use Aniyomi as it's really my go-to app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Secozzi**
Closes #1548

* Adds factory to have multiple of the same extension (the one without a number has the same ID as the old one)
* subtitles will now show correctly for transcoded videos

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt [hunk 1]
```diff
@@ -38,9 +37,9 @@ import uy.kohesive.injekt.injectLazy
 import kotlin.math.ceil
 import kotlin.math.floor
 
-class Jellyfin : ConfigurableAnimeSource, AnimeHttpSource() {
+class Jellyfin(private val suffix: String) : ConfigurableAnimeSource, AnimeHttpSource() {
 
-    override val name = "Jellyfin"
+    override val name = "Jellyfin${suffix.let { if (it.isNotBlank()) " ($it)" else "" }}"
```
Comment (jmir1) [inline src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt:42]:
```suggestion
    override val name = "Jellyfin$suffix"
```

File: src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinFactory.kt [hunk 2]
```diff
@@ -0,0 +1,11 @@
+package eu.kanade.tachiyomi.animeextension.all.jellyfin
+
+import eu.kanade.tachiyomi.animesource.AnimeSourceFactory
+
+class JellyfinFactory : AnimeSourceFactory {
+    override fun createSources() = listOf(
+        Jellyfin(""),
+        Jellyfin("2"),
+        Jellyfin("3"),
```
Comment (jmir1) [inline src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinFactory.kt:9]:
```suggestion
        Jellyfin(" (2)"),
        Jellyfin(" (3)"),
```

**Review by jmir1 — CHANGES_REQUESTED** [review]
Minor nitpick

**Review by jmir1 — APPROVED** [review]
