### PR TITLE
fix(en/gogoanime): Update baseUrl

### LINKED ISSUE #2548: Gogoanime (EN) changed domain
### Source name

Gogoanime(EN)

### Source language

English

### Source link

https://gogoanimehd.io/

### Other details

Opening the website leads to a message where it states that they changed their domain to a new one.

Screenshot_2023-11-25-00-10-20-519-edit_xyz jmir tachiyomi mi debug

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #2548

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt [hunk 1]
```diff
@@ -187,17 +160,15 @@ class GogoAnime : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
...
-        }.flatten().sort().ifEmpty { throw Exception("Failed to extract videos") }
+        return document.select("div.anime_muti_link > ul > li").parallelCatchingFlatMap { server ->
+            val className = server.className()
+            if (!hosterSelection.contains(className)) return@parallelCatchingFlatMap emptyList()
+            val serverUrl = server.selectFirst("a")
+                ?.attr("abs:data-video")
+                ?: return@parallelCatchingFlatMap emptyList()
+
+            getHosterVideos(className, serverUrl)
+        }.sort().ifEmpty { throw Exception("Failed to extract videos") }
```
Comment (Secozzi) [inline src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt:171]: Thanks to your addition to the main app, the ifEmpty check is no longer needed

Comment (Claudemirovsky) [reply src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt:171]: > Thanks to your addition to the main app, the ifEmpty check is no longer needed

Screenshot_20231125_073359
Not my addition but I'll remove it anyway 👍🏽

Comment (Secozzi) [reply src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt]: Since you're overriding `videoListParse` and not `fetchVideoList`, adding `.sort()` isn't necessary either

Comment (Claudemirovsky) [reply src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt]: > Since you're overriding `videoListParse` and not `fetchVideoList`, adding `.sort()` isn't necessary either

I was thinking about that, but I thought there was some kind of strange bug that made it necessary (cursed sources trauma)

**Review by jmir1 — APPROVED** [review]
