### PR TITLE
fix(ar/akwam/faselhd/egydead/tuktukcinema): Mass fix for some arabic extensions

### LINKED ISSUE #992: Akwam arabic
### Source information and language

Akwam 1.8

### Steps to reproduce

Change 
https://akwam.im
To
https://akwam.to

### Expected behavior

https://akwam.to

### Actual behavior

https://akwam.im

### Aniyomi version

0.13.5

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #2195: Akwam/ أكوام
### Source information

ar.akwam  13.8

### Source language

العربية/ Arabic

### Source new URL

https://ak.sv/

### Other details

The domain changed, and now it has one or two other domains (I am actually not sure if it's two separated or one redirect to another) https://ak.sv/ or one.akw.cam

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ahmedgamal17**
add new extractor in tuktukcinema
fix baseurl in faselhd , egydead and akwam

closes #2195
closes #992

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt [hunk 1]
```diff
@@ -151,6 +159,23 @@ class Tuktukcinema : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
...
+                val masterPlaylist = client.newCall(
+                    GET(masterUrl, headers),
+                ).execute().body.string()
+                val separator = "#EXT-X-STREAM-INF:"
+                masterPlaylist.substringAfter(separator).split(separator).forEach {
+                    val quality = it.substringAfter("RESOLUTION=").substringAfter("x").substringBefore(",") + "p "
+                    val videoUrl = m3u8PrimeLink + it.substringAfter("\n").substringBefore("\n")
+                    videoList.add(Video(videoUrl, quality, videoUrl, headers))
+                }
+                return videoList
```
Comment (Secozzi) [inline src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:177]: You don't need to return twice

Comment (Secozzi) [inline src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:177]: Doing it like this is not really a bad thing, but to avoid duplicated code you add a dependency on the `implementation(project(':lib-playlist-utils'))` lib and then it would be:
```suggestion
                PlaylistUtils(client, headers).extractFromHls(masterUrl)
```

File: src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt [hunk 2]
```diff
@@ -100,7 +100,7 @@ class Akwam : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
 
     override fun videoListParse(response: Response): List<Video> {
         val document = response.asJsoup()
-        val iframe = "https://akwam.im/watch" + document.select("a.link-show").attr("href").substringAfter("watch") + "/" + document.ownerDocument()!!.select("input#page_id").attr("value")
+        val iframe = "https://akw-cdn1.link/watch" + document.select("a.link-show").attr("href").substringAfter("watch") + "/" + document.ownerDocument()!!.select("input#page_id").attr("value")
```
Comment (Secozzi) [inline src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt:103]: Why not just do `"$baseUrl/watch"` so you don't have to update the link twice when the site changes domain?

File: src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt [hunk 3]
```diff
@@ -293,7 +318,7 @@ class Tuktukcinema : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
     // preferred quality settings
     private fun getPrefHostUrl(preferences: SharedPreferences): String = preferences.getString(
         "default_domain",
```
Comment (Secozzi) [inline src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:320]: I would suggest changing the key to:
```suggestion
        "default_domain_v${BuildConfig.VERSION_CODE}",
```
This way, the url will be updated for everyone on an extension update.

File: src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt (hunk 1 above)
Comment (ahmedgamal17) [reply src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:177]: is this new lib for m3u8 to extract qualities ohh

File: src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt (hunk 2 above)
Comment (ahmedgamal17) [reply src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt:103]: sometimes i need just change this url as it the site url is different from watch url

File: src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt (hunk 3 above)
Comment (ahmedgamal17) [reply src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:320]: ok the old url is working also but changed it when i made the changes

Comment (Secozzi) [reply src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:320]: I think its better to include the extension version code, as just updating the default doesn't change it if a user has changed it themselves. With this, it's always going to update the url.

File: src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt [hunk 4]
```diff
@@ -151,6 +162,13 @@ class Tuktukcinema : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
 
     private fun extractVideos(url: String): List<Video> {
         return when {
+            url.contains("egtpgrvh") -> {
+                val videoList = mutableListOf<Video>()
+                val request = client.newCall(GET(url, headers)).execute().asJsoup()
+                val data = request.selectFirst("script:containsData(m3u8)")!!.data()
+                val masterUrl = data.substringAfter("sources: [{").substringAfter("file:\"").substringBefore("\"}")
+                PlaylistUtils(client, headers).extractFromHls(masterUrl)
```
Comment (Secozzi) [inline src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt:170]: Might as well use the instance that were lazily created earlier
```suggestion
                playlistUtils.extractFromHls(masterUrl)
```

File: src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt [hunk 5]
```diff
@@ -319,7 +319,7 @@ class EgyDead : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
 
     private fun getPrefHostUrl(preferences: SharedPreferences): String = preferences.getString(
         "default_domain",
```
Comment (Secozzi) [inline src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt:321]:
```suggestion
        "default_domain_v${BuildConfig.VERSION_CODE}",
```

**Review by jmir1 — APPROVED** [review]
