### PR TITLE
Fix(It/StreamingCommunity): Fix empty videolist and change base domain

### LINKED ISSUE #2477: StreamingCommunity Not start video
### Source information

StreamingCommunity 13.2

### Source language

Italiani

### Source new URL

Not changed

### Other details

base override URLs fixed, cache cleaned, cookies, WebView data and restarted, movies and series are all visible, but none of them start, please fix streamcommunity.at in a webview work
Screenshot_2023-11-07-03-43-36-42_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2023-11-07-03-43-59-67_40deb401b9ffe8e1df2f1cc5ba480b12
IMG_20231107_034447

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #3071: StreamingCommunity extension error
### Source information

StreamingCommunity

### Source language

Italian

### Steps to reproduce

Trying to watch a series, update one in library or looking for something new returns error:

SSLHandshakeException

### Expected behavior

Should show data from website streamingcommunity

### Actual behavior

Returns error and doesn't show anything

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Other details

Trying reinstalling previous version to change url fixes fetch of data from website but not fetch of streaming of videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Dark25**
This has been fixed by this guy about 3 months ago or so, I've only changed the domain and other little things.

image

  
  Closes #3071
  Closes #2477
  
  Checklist:
  
  - [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
  - [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
  - [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 1]
```diff
@@ -252,68 +256,81 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
+                .build()
+
+        val iframe =
+            client
+                .newCall(
+                    GET(iframeUrl, headers = iframeHeaders),
+                ).execute()
+                .asJsoup()
+        val scripts = iframe.select("script")
+        val script = scripts.find { it.data().contains("masterPlaylist") }!!.data().replace("\n", "\t")
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:285]:
```suggestion
        val script = iframe.selectFirst("script:containsData(masterPlaylist)")!!.data().replace("\n", "\t")
```

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 2]
```diff
@@ -29,14 +33,14 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
-    // TODO: Check frequency of url changes to potentially
-    // add back overridable baseurl preference
-    override val baseUrl = "https://streamingcommunity.report"
+    override val baseUrl by lazy { preferences.getString(PREF_DOMAIN_KEY, PREF_DOMAIN_DEFAULT)!! }
 
     override val lang = "it"
 
     override val supportsLatest = true
 
+    override val client: OkHttpClient = network.cloudflareClient
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:42]:
```suggestion
    override val client: OkHttpClient = network.client
```

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 3]
```diff
@@ -252,68 +256,81 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
+        val iframe =
+            client
+                .newCall(
+                    GET(iframeUrl, headers = iframeHeaders),
+                ).execute()
+                .asJsoup()
+        val scripts = iframe.select("script")
+        val script = scripts.find { it.data().contains("masterPlaylist") }!!.data().replace("\n", "\t")
+        var playlistUrl = Regex("""url: ?'(.*?)'""").find(script)!!.groupValues[1]
+        val filename = playlistUrl.slice(playlistUrl.lastIndexOf("/") + 1 until playlistUrl.length)
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:286]:
```suggestion
        val filename = playlistUrl.substringAfterLast("/")
```

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 4]
```diff
@@ -252,68 +256,81 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
+
+        val iframe =
+            client
+                .newCall(
+                    GET(iframeUrl, headers = iframeHeaders),
+                ).execute()
+                .asJsoup()
+        val scripts = iframe.select("script")
+        val script = scripts.find { it.data().contains("masterPlaylist") }!!.data().replace("\n", "\t")
+        var playlistUrl = Regex("""url: ?'(.*?)'""").find(script)!!.groupValues[1]
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:285]: Move the regex to a class constant so it doesnt get initialized everytime

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 5]
```diff
@@ -252,68 +256,80 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
 
         // Get subtitles
-        val masterPlUrl = "$playlistUrl?token=$token&expires=$expires&canCast=$canCast&n=1"
-        val masterPl = client.newCall(GET(masterPlUrl)).execute().body.string()
-        val subList = Regex("""#EXT-X-MEDIA:TYPE=SUBTITLES.*?NAME="(.*?)".*?URI="(.*?)"""").findAll(masterPl).map {
-            Track(it.groupValues[2], it.groupValues[1])
-        }.toList()
-
+        val masterPlUrl = "$playlistUrl?token=$token&expires=$expires&n=1"
+        val masterPl =
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:296]: Maybe use the playlistutils lib?

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 6]
```diff
@@ -344,13 +360,33 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
     }
 
     companion object {
+        private const val PREF_DOMAIN_KEY = "referred_domain"
+        private const val PREF_DOMAIN_TITLE = "Override BaseUrl"
+        private const val PREF_DOMAIN_DEFAULT = "https://streamingcommunity.forum"
+        private const val PREF_DOMAIN_SUMMARY = "For temporary uses. Updating the extension will erase this setting."
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:366]: The problem is that this preference doesn't actually get erased on a new extension update, and it really should. Unless you can find a way to do that, I'd advise against adding in such an option. (Also, don't rely on buildconfig for that)

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt (hunk 5 above)
Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:296]: I had to do it manually because I got errors xD

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt (hunk 6 above)
Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:375]: It would only be temporary since this website changes domains like changing shoes

Comment (Secozzi) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:375]: The problem is that the current implementation isn't temporary, and the url won't be updated on an extension update (which it should)

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 7]
```diff
@@ -252,68 +256,89 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
 
     // ============================ Video Links =============================
 
-    override fun videoListRequest(episode: SEpisode): Request = GET("$baseUrl/watch/${episode.url}", headers)
+    object VideoRegex {
+        val PLAYLIST_URL_REGEX = Regex("""url: ?'(.*?)'""")
+        val EXPIRES_REGEX = Regex("""'expires': ?'(\d+)'""")
+        val TOKEN_REGEX = Regex("""'token': ?'([\w-]+)'""")
+        val TOKEN_QUALITY_REGEX = Regex("""'token(\d+p?)': ?'([\w-]+)'""")
+        val SUBTITLES_REGEX = Regex("""#EXT-X-MEDIA:TYPE=SUBTITLES.*?NAME="(.*?)".*?URI="(.*?)"""")
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:264]: Move these to the companion object and make them private

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 8]
```diff
@@ -252,68 +256,89 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
+    }
 
-    override fun videoListParse(response: Response): List<Video> {
-        val data = json.decodeFromString<VideoResponse>(response.asJsoup().getData())
+    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getVideoList"))
+    override fun fetchVideoList(episode: SEpisode): Observable<List<Video>> {
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:268]: override getVideoList instead of fetchVideoList

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt (hunk 7 above)
Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt]: ok

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt (hunk 8 above)
Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt]: ready

Comment (Secozzi) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt]: Not yet :)

Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt]: Now yes :)

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 9]
```diff
@@ -252,68 +253,83 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
...
+                    append("&expires=$expires")
+                    append("&n=1")
+                }
             videoList.add(Video(videoUrl, quality, videoUrl, subtitleTracks = subList))
         }
 
         require(videoList.isNotEmpty()) { "Failed to fetch videos" }
 
-        return videoList.sort()
+        return videoList
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:326]: You still need to sort the list here

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt [hunk 10]
```diff
@@ -252,68 +253,83 @@ class StreamingCommunity : ConfigurableAnimeSource, AnimeHttpSource() {
 
     // ============================ Video Links =============================
 
-    override fun videoListRequest(episode: SEpisode): Request = GET("$baseUrl/watch/${episode.url}", headers)
+    interface VideoProvider {
+        fun getVideoList(): List<Video>
+    }
```
Comment (Secozzi) [inline src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt:258]: What's the point of this?

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt (hunk 9 above)
Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt]: Ready

File: src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt (hunk 10 above)
Comment (Dark25) [reply src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt]: I was testing something and I missed deleting it

**Review by jmir1 — APPROVED** [review]

**Comment by SplendideMendax** [comment]
As I have already written, I have never studied programming and I apologize for not having updated the post on the problems encountered in the following days of use.  Mainly 3 things happen: the subtitles repeat the same sentence 4-5 times, some episodes freeze and some have no audio.  I was mainly driven by finishing watching a TV series and didn't make sure that what I didn't need worked.  I apologize for the inconvenience caused.
