### PR TITLE
fix(lib/voe-extractor): Voe extractor fixed

### LINKED ISSUE #3180: Voe extractor not working
### Source information

Serienstream (14.16), Aniworld (14.22), Animetoast (14.12)

### Source language

German

### Steps to reproduce

Try to play any Video/Stream on those extensions. (For Serienstream: you need to be logged in)

### Expected behavior

The video should play.

### Actual behavior

I get an Toast notification pop-up and the player closes while no video loads: 
`Expected URL scheme 'http' or 'https' but no
scheme was found for aHROcH...`

### Aniyomi version

App version: 0.15.2.4 (standard, 16361e5, 121, 2024-01-28T19:30Z) 

### Android version

Android 14

### Other details

The websites and Webview work normally. What I did notice is, that all extensions use VOE as the Video source. But even when I change it to the other options, they dont work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by imper1aldev**
Checklist:

Closes #3180

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib/voe-extractor/src/main/java/eu/kanade/tachiyomi/lib/voeextractor/VoeExtractor.kt [hunk 1]
```diff
@@ -27,7 +27,9 @@ class VoeExtractor(private val client: OkHttpClient) {
         val playlistUrl = when {
             // Layout 1
             script.contains("sources") -> {
-                script.substringAfter("hls': '").substringBefore("'")
+                val link = script.substringAfter("hls': '").substringBefore("'")
+                val linkRegex = "(http|https)://([\\w_-]+(?:\\.[\\w_-]+)+)([\\w.,@?^=%&:/~+#-]*[\\w@?^=%&/~+#-])".toRegex()
```
Comment (Secozzi) [inline lib/voe-extractor/src/main/java/eu/kanade/tachiyomi/lib/voeextractor/VoeExtractor.kt:31]: Move the regex to a class instance to prevent repeated initializations

**Review by jmir1 — APPROVED** [review]
