### PR TITLE
fix(pt/betteranime): Fix http 405 on search + add automatic login

### LINKED ISSUE #2767: Betteranime (pt br) extension issues error 405 when searching.
### Source information

Betteranime 14.8

### Source language

Português (Brasil)

### Steps to reproduce

When doing any search on the Betteranime (pt br) extension, HTTP 405 appears.

### Expected behavior

The search result should appear.

### Actual behavior

HTTP error 405 appears.

### Aniyomi version

r7454

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #2811: BetterAnime is dead
### Source name

Better Anime

### Source language

Portuguese

### Source link

https://betteranime.net

### Other details

Closed due to DMCA 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #2811 
Closes #2767 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Hates kotlinx.serialization

### CODE REVIEW

File: src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BetterAnime.kt [hunk 1]
```diff
@@ -129,38 +106,88 @@ class BetterAnime : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
...
+
+    private fun updateSnapshot(request: Request) {
+        val document = client.newCall(request).execute().asJsoup()
+        val wireElement = document.selectFirst("[wire:snapshot]")!!
+        snapshot = wireElement.attr("wire:snapshot")
+        wireToken = document.selectFirst("script[data-csrf]")!!.attr("data-csrf")
+    }
+
+    override fun searchAnimeParse(response: Response): AnimesPage {
+        val body = response.body.string()
```
Comment (Secozzi) [inline src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BetterAnime.kt:176]:
```suggestion
        val body = response.use { it.body.string() }
```

Comment (Claudemirovsky) [reply src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BetterAnime.kt:176]: According to [OkHttp's docs](https://square.github.io/okhttp/5.x/okhttp/okhttp3/-response-body/index.html), `.string()` already closes the response body.

**Review by jmir1 — APPROVED** [review]
