### PR TITLE
fix(src/es): Fix video extraction and fix json parsing

### LINKED ISSUE #3099: Doramasflix Recent Error
### Source information

Doramasflix 14.18 (Spanish)

### Source language

Spanish

### Steps to reproduce

1. Open the extension 
2. Enter recent 
3. Error JsonDecodingException 

### Expected behavior

You should view the recent dramas

### Actual behavior

I have opened the extension and in the (recent) doramas section I get jsonDecodingException

### Aniyomi version

Preview r7513

### Android version

Android 13

### Other details

Screenshot_20240325_080010_Aniyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #3136: the extension doesn't load all the servers (jkanime)
### Source information

Jkanime 14.19

### Source language

Spanish

### Steps to reproduce

1 open Jkanime
2 find any anime
3 play any chapter

### Expected behavior

may the extension be able to load all the servers

### Actual behavior

the extension only loads 2 servers (desu, xtreme s) and 2 show the "loading failed" mesage.

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by imper1aldev**
Checklist:

Closes #3099
Closes #3136

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt [hunk 1]
```diff
@@ -114,33 +124,64 @@ class Jkanime : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
...
-                    "stream/jkmedia" in url -> videos.add(Video(url, "$lang Xtreme S", url))
-                    "um2.php" in url -> JkanimeExtractor(client).getNozomiFromUrl(baseUrl + url, "$lang ").let { if (it != null) videos.add(it) }
-                    "um.php" in url -> JkanimeExtractor(client).getDesuFromUrl(baseUrl + url, "$lang ").let { if (it != null) videos.add(it) }
-                }
-            } catch (_: Exception) {}
+    override fun videoListParse(response: Response): List<Video> {
+        val document = response.asJsoup()
+        return getVideoLinks(document).parallelCatchingFlatMapBlocking { (url, lang) ->
+            when {
+                "ok" in url -> OkruExtractor(client).videosFromUrl(url, "$lang ")
```
Comment (Secozzi) [inline src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt:171]: Move the extractors out to a class instance so they don't get initialized every time

File: src/es/doramasflix/src/eu/kanade/tachiyomi/animeextension/es/doramasflix/DataModel.kt [hunk 2]
```diff
@@ -139,7 +139,7 @@ data class Item(
     val cast: List<Cast> = emptyList(),
     val names: String?,
     val overview: String?,
-    val languages: List<String> = emptyList(),
+    val languages: List<String?>? = emptyList(),
```
Comment (Secozzi) [inline src/es/doramasflix/src/eu/kanade/tachiyomi/animeextension/es/doramasflix/DataModel.kt:142]: Is this field not used in the main class?

File: src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt [hunk 3]
```diff
@@ -114,33 +124,74 @@ class Jkanime : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
...
+    private fun String.getLang(): String {
+        return languages.firstOrNull { it.first == this }?.second ?: ""
+    }
+
+    private fun getVideoLinks(document: Document): MutableList<Pair<String, String>> {
+        val servers = mutableListOf<Pair<String, String>>()
+        val scriptServers = document.selectFirst("script:containsData(var video = [];)")!!
+
+        val jsServer = scriptServers.data().substringAfter("var remote = '").substringBefore("'")
+        val jsPath = scriptServers.data().substringAfter("= remote+'").substringBefore("'")
```
Comment (Secozzi) [inline src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt:142]:
```suggestion
        val scriptServers = document.selectFirst("script:containsData(var video = [];)")!!.data()

        val jsServer = scriptServers.substringAfter("var remote = '").substringBefore("'")
        val jsPath = scriptServers.substringAfter("= remote+'").substringBefore("'")
```

File: src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/extractors/JkanimeExtractor.kt [hunk 4]
```diff
@@ -42,4 +42,14 @@ class JkanimeExtractor(
         }
         return null
     }
+
+    fun getDesukaFromUrl(url: String, prefix: String = ""): Video? {
```
Comment (Secozzi) [inline src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/extractors/JkanimeExtractor.kt:46]: Since you're using `!!` after calling the function anyways, make it return `List<Video>` instead and return an emptyList instead of null

**Review by jmir1 — APPROVED** [review]
