### PR TITLE
fix(pt/goanimes): Fix video extractor

### LINKED ISSUE #2285: GO ANIMES
### Source information

Goanimes 13.3

### Source language

PT BR 

### Steps to reproduce

Não faz download nenhum episódio 

### Expected behavior

Começar a baixar o episódio 

### Actual behavior

Screenshot_20230930-082618

### Aniyomi version

App version: 0.14.3-6151 (standard, 43e8dcd1f, 94, 2023-06-15T08:44Z) Android version: 10 (SDK 29) Android build ID: QPZS30.30-Q3-38-69-12 Device brand: motorola Device manufacturer: motorola Device name: guam Device model: moto e(7) plus Device product name: guam_retail

### Android version

10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #2285 
Checklist:

- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by jmir1 — APPROVED** [review]

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt [hunk 1]
```diff
@@ -15,14 +15,13 @@ class DooPlayGenerator : ThemeSourceGenerator {
         SingleLang("AnimeOnline.Ninja", "https://ww3.animeonline.ninja", "es", className = "AnimeOnlineNinja", isNsfw = false, overrideVersionCode = 33),
         SingleLang("AnimesOnline", "https://animesonline.nz", "pt-BR", isNsfw = false, overrideVersionCode = 5, pkgName = "animesgratis"),
         SingleLang("AnimePlayer", "https://animeplayer.com.br", "pt-BR", isNsfw = true, overrideVersionCode = 1),
-        SingleLang("AnimePlayer", "https://animeplayer.com.br", "pt-BR", isNsfw = true),
```
Comment (jmir1) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt:18]: why this?

Comment (Claudemirovsky) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt:18]: As you can see, it was a duplicated line, so i removed the useless one.

Comment (jmir1) [reply multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt:18]: > As you can see, it was a duplicated line, so i removed the useless one.

Bold of you to assume that I can read.

I missed that LOL
