### PR TITLE
fix(all/yomiroll): Fetch anime status from AniList.co

### LINKED ISSUE #2326: Ongoing Anime labelled as completed in yomiroll
### Source information

Yomiroll 13.24

### Source language

Multi

### Steps to reproduce

1. Find an ongoing anime
2. Add it to library

### Expected behavior

Be labelled as ongoing 

### Actual behavior

Is labelled completed 

### Aniyomi version

Preview r6668

### Android version

Android 13

### Other details

This wouldn't have been a problem but the latest preview added a new feature called "Show next episode's airing time". Problem is that even if the anime is currently releasing, if the sources mislabel it as completed the app would also think it's completed and won't display the airing date.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mklive**
Closes #2326 

Uses API provided by Anilist.co (https://anilist.github.io/ApiV2-GraphQL-Docs/) to fetch series status as CR won't track for itself. Inspired by https://github.com/aniyomiorg/aniyomi-extensions/pull/2055/files

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt [hunk 1]
```diff
@@ -125,6 +129,52 @@ class Yomiroll : ConfigurableAnimeSource, AnimeHttpSource() {
 
     // =========================== Anime Details ============================
 
+    // Function to fetch anime status using AniList GraphQL API ispired by OppaiStream.kt
+    private fun fetchStatusByTitle(title: String): Int {
+        val client = OkHttpClient()
```
Comment (Claudemirovsky) [inline src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:134]: You should use the source's `OkHttpClient` instance (= the `client` val that already exists). 
Just deleting this line should be enough.
```suggestion
```

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt [hunk 2]
```diff
@@ -125,6 +129,52 @@ class Yomiroll : ConfigurableAnimeSource, AnimeHttpSource() {
...
+        """.trimIndent()
+
+        val requestBody = FormBody.Builder()
+            .add("query", query)
+            .build()
+
+        val request = Request.Builder()
+            .url("https://graphql.anilist.co")
+            .post(requestBody)
+            .build()
```
Comment (Claudemirovsky) [inline src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:158]: The [extensions-lib](https://github.com/aniyomiorg/extensions-lib) provides a function that builds POST requests for you: it's [eu.kanade.tachiyomi.network.POST](https://extension-docs.aniyomi.org/extensions-lib/eu.kanade.tachiyomi.network/-p-o-s-t.html). Import it and you'll be able to write this:
```suggestion
        val request = POST("https://graphql.anilist.co", requestBody)
```

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt [hunk 3]
```diff
@@ -58,6 +58,7 @@ data class Anime(
     @SerialName("keywords")
     val genres: ArrayList<String>? = null,
     val series_metadata: Metadata? = null,
+    val is_simulcast: Boolean? = null,
```
Comment (Claudemirovsky) [inline src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt:61]: Sorry if I'm being blind, but I didn't find a line of code using this variable.

**Review by Claudemirovsky — CHANGES_REQUESTED** [review]

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt (hunk 3 above)
Comment (Samfun75) [reply src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt]: yeah you're right it's not used

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt [hunk 4]
```diff
@@ -365,7 +404,7 @@ class Yomiroll : ConfigurableAnimeSource, AnimeHttpSource() {
             url = LinkData(id, type!!).toJsonString()
             genre = series_metadata?.genres?.joinToString()
                 ?: movie_metadata?.genres?.joinToString() ?: ""
-            status = SAnime.COMPLETED
+            status = fetchStatusByTitle(this@toSAnime.title)
```
Comment (Samfun75) [inline src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:407]: this will cause 429 too many request, will adjust in #2735 after merge

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt (hunk 1 above)
Comment (Samfun75) [reply src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt]: the crunchy token in the interceptor is causing issues with anilist, this needs to be added back XD

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt [hunk 5]
```diff
@@ -65,6 +71,10 @@ class Yomiroll : ConfigurableAnimeSource, AnimeHttpSource() {
         super.client.newBuilder().addInterceptor(tokenInterceptor).build()
     }
 
+    private val noTokenClient by lazy {
+        super.client.newBuilder().build()
+    }
```
Comment (jmir1) [inline src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:76]: This is a nitpick but you don't have to build a new client, you can just do

```suggestion
    private val noTokenClient = super.client
```

**Review by jmir1 — CHANGES_REQUESTED** [review]

**Review by jmir1 — APPROVED** [review]

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt [hunk 6]
```diff
@@ -355,55 +400,69 @@ class Yomiroll : ConfigurableAnimeSource, AnimeHttpSource() {
...
-            desc += if (series_metadata?.is_simulcast == true) "\nSimulcast" else ""
-            desc += "\n\nAudio: " + (
-                series_metadata?.audio_locales?.sortedBy { it.getLocale() }
-                    ?.joinToString { it.getLocale() } ?: ""
+            url = anime?.url ?: LinkData(id, type!!).toJsonString()
+            genre = anime?.genre ?: (series_metadata?.genres ?: movie_metadata?.genres ?: genres)
+                ?.joinToString { gen -> gen.replaceFirstChar { it.uppercase() } }
+            status = if (anime != null) fetchStatusByTitle(this@toSAnime.title) else SAnime.UNKNOWN
+            author = content_provider
+            description = anime?.description ?: StringBuilder().apply {
```
Comment (Claudemirovsky) [inline src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:416]: (not so) fun fact: you can use kotlin's [`buildString {}`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/build-string.html) block instead of `StringBuilder().apply {}.toString()`. In practice it's the same thing, just slightly more readable.

**Review by Claudemirovsky — APPROVED** [review]

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt (hunk 5 above)
Comment (Samfun75) [reply src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt]: Isn't the default client the cloudflare one? That was my thought But I guess it doesn't matter here. Thanks

File: src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt (hunk 6 above)
Comment (Samfun75) [reply src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:416]: Ig jmir the second forgot to change this. And ayo why did you block friend requests? Are the ppl in the server bothering you 😂

Comment (Samfun75) [reply src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt:416]:
```suggestion
            description = StringBuilder().apply {
```
forgotten to remove this after my experiment and now description is loaded once, and languages won't update if CR add new ones, I'll wait till someone notices to change it XP
