### PR TITLE
fix(en/oppaistream): Fix episode list and video extractor

### LINKED ISSUE #2241: oppai stream is not working
### Source information

oppai stream 13.2

### Source language

english

### Steps to reproduce

1. Select "oppai stream" from the sources.
2. Select an appropriate animation in the list.
3. The page of the animation will be loaded.

### Expected behavior

The episode should appear.

### Actual behavior

In fact, it becomes an episode notfound.

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #2241 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensionss
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/oppaistream/src/eu/kanade/tachiyomi/animeextension/en/oppaistream/OppaiStream.kt [hunk 1]
```diff
@@ -269,54 +220,124 @@ class OppaiStream : ParsedAnimeHttpSource(), ConfigurableAnimeSource {
...
+
+        return parseThumbnailUrlFromObject(response.parseAs<AnilistResponseDto>())
+    }
+
+    private fun parseThumbnailUrlFromObject(obj: AnilistResponseDto): Pair<String, List<String>>? {
+        val media = obj.data.media ?: return null
+
+        val coverURL = when (preferences.getString(PREF_COVER_QUALITY_KEY, PREF_COVER_QUALITY_DEFAULT)) {
+            "extraLarge" -> media.coverImage.extraLarge
+            else -> media.coverImage.extraLarge
```
Comment (AwkwardPeak7) [inline src/en/oppaistream/src/eu/kanade/tachiyomi/animeextension/en/oppaistream/OppaiStream.kt:310]:
```suggestion
            else -> media.coverImage.large
```

Comment (Claudemirovsky) [reply src/en/oppaistream/src/eu/kanade/tachiyomi/animeextension/en/oppaistream/OppaiStream.kt]: Thanks!

**Review by jmir1 — APPROVED** [review]
